ALTER TABLE  "VOLUNTEERS_TIME_SLOT_TYPE_LIMITS" ADD CONSTRAINT "VOLUNTEERS_TIME_SLOT_TYPE_LIMITS_FK" FOREIGN KEY ("VOLUNTEERS_TIME_SLOTS_ID")
	  REFERENCES  "VOLUNTEERS_TIME_SLOTS" ("ID") ON DELETE CASCADE ENABLE;
/